# Generated by Django 3.2.23 on 2023-11-23 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('DeptID', models.AutoField(db_column='deptid', editable=False, primary_key=True, serialize=False)),
                ('DeptNumber', models.CharField(db_column='deptnumber', help_text='最大长度不超过40个字符,修改部门编号后不会改变人员所在的部门。', max_length=40, verbose_name='部门编号')),
                ('DeptName', models.CharField(db_column='deptname', max_length=40, verbose_name='部门编号')),
                ('parent', models.IntegerField(blank=True, db_column='supdeptid', default=0, verbose_name='父部门编号')),
                ('DeptAddr', models.CharField(blank=True, db_column='deptaddr', max_length=50, null=True, verbose_name='部门地址')),
                ('DeptPerson', models.CharField(blank=True, db_column='deptperson', max_length=20, null=True, verbose_name='联系人')),
                ('DeptPhone', models.CharField(blank=True, db_column='deptphone', max_length=20, null=True, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('DelTag', models.IntegerField(blank=True, db_column='deltag', default=0, editable=False, null=True, verbose_name='删除标记')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'db_table': 'departments',
                'default_permissions': ('add', 'change', 'delete', 'export'),
                'unique_together': {('DeptNumber',)},
            },
        ),
        migrations.CreateModel(
            name='UserEmp',
            fields=[
                ('id', models.AutoField(db_column='userid', editable=False, primary_key=True, serialize=False)),
                ('badgenumber', models.CharField(db_column='badgenumber', max_length=24, verbose_name='人员编号')),
                ('ename', models.CharField(blank=True, db_column='ename', default='', max_length=24, null=True, verbose_name='人员姓名')),
                ('isstaff', models.BooleanField(db_column='isstaff', default=False, verbose_name='是否可以登陆状态')),
                ('isactive', models.BooleanField(db_column='isactive', default=False, verbose_name='是否有所有权限')),
                ('isadmin', models.BooleanField(db_column='isadmin', default=False, verbose_name='是否是管理员')),
                ('empemail', models.EmailField(blank=True, db_column='empemail', default='', max_length=254, null=True, verbose_name='邮箱')),
                ('phono', models.CharField(blank=True, db_column='email', default='', max_length=24, null=True, verbose_name='邮箱')),
                ('defaultdeptid', models.ForeignKey(db_column='defaultdeptid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employee.department', verbose_name='部门')),
            ],
            options={
                'verbose_name': '人员',
                'verbose_name_plural': '人员',
                'db_table': 'userinfo',
                'default_permissions': ('browse', 'add', 'change', 'delete', 'export'),
                'unique_together': {('badgenumber',)},
            },
        ),
    ]
