# Generated by Django 3.2.23 on 2023-12-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='DeptName',
            field=models.CharField(db_column='deptname', max_length=40, verbose_name='部门名称'),
        ),
    ]
