# Generated by Django 3.2.23 on 2023-11-23 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuserapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='date_of_birth',
        ),
    ]
