# Generated by Django 3.2.23 on 2023-12-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='类别编码')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='类别名称')),
                ('symbol', models.CharField(blank=True, max_length=30, null=True, verbose_name='类别符号')),
                ('ascription', models.CharField(choices=[('0', '固定资产'), ('1', '低值易耗品')], max_length=2, null=True, verbose_name='类别归属')),
                ('pidparent', models.IntegerField(blank=True, db_column='pidparent', null=True, verbose_name='上级类别')),
                ('attach_code', models.IntegerField(blank=True, default=0, editable=False, null=True)),
                ('deltag', models.IntegerField(default=0, editable=False, verbose_name='删除')),
            ],
            options={
                'verbose_name': '资产类别',
                'verbose_name_plural': '资产类别',
                'db_table': 'assetclass',
                'default_permissions': ('add', 'change', 'delete', 'export'),
                'unique_together': {('code',)},
            },
        ),
    ]
